name: Generate and Submit ZK Proof

on:
  push:
    branches: [ main ]

jobs:
  build-and-submit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install circomlib snarkjs axios

    # --- ZK STEPS TEMPORARILY DISABLED FOR DEBUGGING ---
    # - name: Compile circuit
    #   run: cat proof_circuit.circom | npx circom - --r1cs --wasm --sym -o .
    # - name: Download Powers of Tau file
    #   run: wget https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_12.ptau -O pot12_final.ptau
    # --- END OF DISABLED STEPS ---

    - name: Run the simple test script
      run: node submit.js